---
name: 'CI'

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2 2,16 * *'

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'docker/setup-qemu-action@v1'
      - uses: 'docker/setup-buildx-action@v1'

      - name: 'Login to DockerHub'
        uses: 'docker/login-action@v1'
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Pre-build dev container image'
        uses: devcontainers/ci@v0.3
        with:
          imageName: 'lacrif/ansible-devcontainer'
          platform: 'linux/amd64,linux/arm64'
          imageTag: 'latest,11'
          push: always
